"""Add forecast_events table

Revision ID: b061dc69d000
Revises: b5a9b2fd536a
Create Date: 2026-03-14 09:25:55.783254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b061dc69d000'
down_revision: Union[str, Sequence[str], None] = 'b5a9b2fd536a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('sales') as batch_op:
        batch_op.drop_constraint('uq_sales_date_sku', type_='unique')
        batch_op.create_unique_constraint('uq_sales_org_date_sku', ['organization_id', 'date', 'sku_id'])
        batch_op.create_foreign_key('fk_sales_org_sku', 'skus', ['organization_id', 'sku_id'], ['organization_id', 'sku_id'], ondelete='CASCADE')

    with op.batch_alter_table('skus') as batch_op:
        batch_op.create_unique_constraint('uq_skus_org_sku', ['organization_id', 'sku_id'])

    # Drop the unique=True index to replace it with a non-unique one
    with op.batch_alter_table('skus') as batch_op:
        batch_op.drop_index('ix_skus_sku_id')
        batch_op.create_index('ix_skus_sku_id', ['sku_id'], unique=False)

    # Actually create the forecast_events table!
    op.create_table('forecast_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_days', sa.Integer(), nullable=False),
    sa.Column('current_inventory', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('supplier_pack_size', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_events_category_timestamp', 'forecast_events', ['category', 'timestamp'], unique=False)
    op.create_index('ix_forecast_events_org_timestamp', 'forecast_events', ['organization_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_forecast_events_category'), 'forecast_events', ['category'], unique=False)
    op.create_index(op.f('ix_forecast_events_organization_id'), 'forecast_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forecast_events_timestamp'), 'forecast_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_events_organization_id'), table_name='upload_events')
    op.drop_index('ix_upload_events_org_category_uploaded_at', table_name='upload_events')
    op.drop_constraint('uq_skus_org_sku', 'skus', type_='unique')
    op.drop_index(op.f('ix_skus_organization_id'), table_name='skus')
    op.drop_index('ix_skus_org_category', table_name='skus')
    op.drop_index(op.f('ix_skus_sku_id'), table_name='skus')
    op.create_index(op.f('ix_skus_sku_id'), 'skus', ['sku_id'], unique=1)
    op.drop_index(op.f('ix_shopify_stores_organization_id'), table_name='shopify_stores')
    op.drop_constraint('fk_sales_org_sku', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'skus', ['sku_id'], ['sku_id'], ondelete='CASCADE')
    op.drop_constraint('uq_sales_org_date_sku', 'sales', type_='unique')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_index('ix_sales_org_date', table_name='sales')
    op.create_unique_constraint(op.f('uq_sales_date_sku'), 'sales', ['date', 'sku_id'])
    op.drop_index(op.f('ix_recommendation_logs_organization_id'), table_name='recommendation_logs')
    op.drop_index('ix_recommendation_logs_org_timestamp', table_name='recommendation_logs')
    op.drop_index(op.f('ix_forecast_cache_organization_id'), table_name='forecast_cache')
    op.drop_index('ix_forecast_cache_org_category', table_name='forecast_cache')
    # ### end Alembic commands ###
