"""baseline schema

Revision ID: b5a9b2fd536a
Revises: 
Create Date: 2026-03-13 08:31:35.090577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a9b2fd536a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_forecast_cache_org_category', 'forecast_cache', ['organization_id', 'category'], unique=False)
    op.create_index(op.f('ix_forecast_cache_organization_id'), 'forecast_cache', ['organization_id'], unique=False)
    op.create_index('ix_recommendation_logs_org_timestamp', 'recommendation_logs', ['organization_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_organization_id'), 'recommendation_logs', ['organization_id'], unique=False)
    op.drop_constraint(op.f('uq_sales_date_sku'), 'sales', type_='unique')
    op.create_index('ix_sales_org_date', 'sales', ['organization_id', 'date'], unique=False)
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_sales_org_date_sku', 'sales', ['organization_id', 'date', 'sku_id'])
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('fk_sales_org_sku', 'sales', 'skus', ['organization_id', 'sku_id'], ['organization_id', 'sku_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_shopify_stores_organization_id'), 'shopify_stores', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_skus_sku_id'), table_name='skus')
    op.create_index(op.f('ix_skus_sku_id'), 'skus', ['sku_id'], unique=False)
    op.create_index('ix_skus_org_category', 'skus', ['organization_id', 'category'], unique=False)
    op.create_index(op.f('ix_skus_organization_id'), 'skus', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_skus_org_sku', 'skus', ['organization_id', 'sku_id'])
    op.create_index('ix_upload_events_org_category_uploaded_at', 'upload_events', ['organization_id', 'category', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_upload_events_organization_id'), 'upload_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_events_organization_id'), table_name='upload_events')
    op.drop_index('ix_upload_events_org_category_uploaded_at', table_name='upload_events')
    op.drop_constraint('uq_skus_org_sku', 'skus', type_='unique')
    op.drop_index(op.f('ix_skus_organization_id'), table_name='skus')
    op.drop_index('ix_skus_org_category', table_name='skus')
    op.drop_index(op.f('ix_skus_sku_id'), table_name='skus')
    op.create_index(op.f('ix_skus_sku_id'), 'skus', ['sku_id'], unique=1)
    op.drop_index(op.f('ix_shopify_stores_organization_id'), table_name='shopify_stores')
    op.drop_constraint('fk_sales_org_sku', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'skus', ['sku_id'], ['sku_id'], ondelete='CASCADE')
    op.drop_constraint('uq_sales_org_date_sku', 'sales', type_='unique')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_index('ix_sales_org_date', table_name='sales')
    op.create_unique_constraint(op.f('uq_sales_date_sku'), 'sales', ['date', 'sku_id'])
    op.drop_index(op.f('ix_recommendation_logs_organization_id'), table_name='recommendation_logs')
    op.drop_index('ix_recommendation_logs_org_timestamp', table_name='recommendation_logs')
    op.drop_index(op.f('ix_forecast_cache_organization_id'), table_name='forecast_cache')
    op.drop_index('ix_forecast_cache_org_category', table_name='forecast_cache')
    # ### end Alembic commands ###
